<?php

declare(strict_types=1);

/**
 * Tipi di U-Boot — dati tecnici storici.
 *
 * Ogni riga porta `fonte` e `confidence`. Dove la letteratura da' valori
 * discordi (tipico per la quota di collasso) si registra l'INTERVALLO
 * crush_depth_min_m / crush_depth_max_m, non una media inventata.
 *
 * Le due autonomie (range1/range2) servono a calibrare il consumo: con due
 * punti si ricavano le costanti della curva "consumo orario = a + b·v³"
 * senza inventare nulla (vedi Sim\Consumption). Dove il secondo punto non e'
 * documentato, il modulo usa la proporzione ricavata dal Tipo VII C.
 */

return [
    [
        'type_key' => 'IID', 'name' => 'Tipo II D', 'soprannome' => 'Einbaum (la piroga)',
        'disp_surf_t' => 314, 'disp_sub_t' => 364,
        'speed_surf_kn' => 12.7, 'speed_sub_kn' => 7.4,
        'fuel_t' => 38.0,
        'range1_nm' => 5650, 'range1_kn' => 8.0, 'range2_nm' => null, 'range2_kn' => null,
        'sub_range_nm' => 56, 'sub_range_kn' => 4.0, 'sub_max_hours' => 1.2,
        'test_depth_m' => 100, 'crush_depth_min_m' => 150, 'crush_depth_max_m' => 200,
        'dive_time_s' => 25, 'crew_min' => 22, 'crew_max' => 25,
        'torpedoes' => 5, 'tubes_bow' => 3, 'tubes_stern' => 0,
        'deck_gun' => null, 'provisions_days' => 21,
        'unlock_rank' => 0, 'playable' => 1,
        'fonte' => 'Specifiche costruttive dei battelli costieri Tipo II serie D (1940-41).',
        'confidence' => 'media',
        'note' => 'Battello costiero, addestramento e Mare del Nord. Poca autonomia, pochi siluri, nessun cannone di coperta: il banco di prova dei comandanti nuovi.',
    ],
    [
        'type_key' => 'VIIB', 'name' => 'Tipo VII B', 'soprannome' => null,
        'disp_surf_t' => 753, 'disp_sub_t' => 857,
        'speed_surf_kn' => 17.9, 'speed_sub_kn' => 8.0,
        'fuel_t' => 108.3,
        'range1_nm' => 8700, 'range1_kn' => 10.0, 'range2_nm' => 6500, 'range2_kn' => 12.0,
        'sub_range_nm' => 90, 'sub_range_kn' => 4.0, 'sub_max_hours' => 1.5,
        'test_depth_m' => 100, 'crush_depth_min_m' => 220, 'crush_depth_max_m' => 250,
        'dive_time_s' => 30, 'crew_min' => 44, 'crew_max' => 48,
        'torpedoes' => 14, 'tubes_bow' => 4, 'tubes_stern' => 1,
        'deck_gun' => '8,8 cm SK C/35', 'provisions_days' => 42,
        'unlock_rank' => 1, 'playable' => 1,
        'fonte' => 'Specifiche Tipo VII B; e\' il battello dei comandanti del primo periodo (Prien, Schepke, Kretschmer).',
        'confidence' => 'media',
        'note' => 'Piu\' veloce e con piu\' nafta del VII C grazie alle casse laterali: il migliore dei Tipo VII per autonomia.',
    ],
    [
        'type_key' => 'VIIC', 'name' => 'Tipo VII C', 'soprannome' => 'il cavallo da tiro',
        'disp_surf_t' => 769, 'disp_sub_t' => 871,
        'speed_surf_kn' => 17.7, 'speed_sub_kn' => 7.6,
        'fuel_t' => 113.5,
        'range1_nm' => 8500, 'range1_kn' => 10.0, 'range2_nm' => 6500, 'range2_kn' => 12.0,
        'sub_range_nm' => 80, 'sub_range_kn' => 4.0, 'sub_max_hours' => 1.5,
        'test_depth_m' => 100, 'crush_depth_min_m' => 220, 'crush_depth_max_m' => 250,
        'dive_time_s' => 30, 'crew_min' => 44, 'crew_max' => 52,
        'torpedoes' => 14, 'tubes_bow' => 4, 'tubes_stern' => 1,
        'deck_gun' => '8,8 cm SK C/35', 'provisions_days' => 42,
        'unlock_rank' => 2, 'playable' => 1,
        'fonte' => 'Specifiche Tipo VII C: il battello piu' . "'" . ' costruito della guerra (568 unita\' circa).',
        'confidence' => 'alta',
        'note' => 'Il battello della Battaglia dell\'Atlantico. Quattordici siluri di cui tre in contenitori stagni esterni, imbarcabili solo con mare calmo e diverse ore di lavoro.',
    ],
    [
        'type_key' => 'VIIC41', 'name' => 'Tipo VII C/41', 'soprannome' => null,
        'disp_surf_t' => 759, 'disp_sub_t' => 860,
        'speed_surf_kn' => 17.7, 'speed_sub_kn' => 7.6,
        'fuel_t' => 113.5,
        'range1_nm' => 8500, 'range1_kn' => 10.0, 'range2_nm' => 6500, 'range2_kn' => 12.0,
        'sub_range_nm' => 80, 'sub_range_kn' => 4.0, 'sub_max_hours' => 1.5,
        'test_depth_m' => 120, 'crush_depth_min_m' => 250, 'crush_depth_max_m' => 280,
        'dive_time_s' => 30, 'crew_min' => 44, 'crew_max' => 52,
        'torpedoes' => 14, 'tubes_bow' => 4, 'tubes_stern' => 1,
        'deck_gun' => '8,8 cm SK C/35', 'provisions_days' => 42,
        'unlock_rank' => 4, 'playable' => 1,
        'fonte' => 'Specifiche Tipo VII C/41: scafo resistente alleggerito e irrobustito.',
        'confidence' => 'media',
        'note' => 'Stesso battello del VII C con scafo capace di scendere piu\' a fondo: nel 1943 la profondita\' non e\' un lusso, e\' la vita.',
    ],
    [
        'type_key' => 'IXB', 'name' => 'Tipo IX B', 'soprannome' => null,
        'disp_surf_t' => 1051, 'disp_sub_t' => 1178,
        'speed_surf_kn' => 18.2, 'speed_sub_kn' => 7.3,
        'fuel_t' => 165.0,
        'range1_nm' => 12000, 'range1_kn' => 10.0, 'range2_nm' => null, 'range2_kn' => null,
        'sub_range_nm' => 64, 'sub_range_kn' => 4.0, 'sub_max_hours' => 1.4,
        'test_depth_m' => 100, 'crush_depth_min_m' => 200, 'crush_depth_max_m' => 230,
        'dive_time_s' => 35, 'crew_min' => 48, 'crew_max' => 56,
        'torpedoes' => 22, 'tubes_bow' => 4, 'tubes_stern' => 2,
        'deck_gun' => '10,5 cm SK C/32', 'provisions_days' => 56,
        'unlock_rank' => 5, 'playable' => 1,
        'fonte' => 'Specifiche Tipo IX B, battello oceanico d\'altura.',
        'confidence' => 'media',
        'note' => 'Autonomia da Caraibi e Africa occidentale, ma immersione rapida piu\' lenta di cinque secondi buoni: contro gli aerei sono un\'eternita\'.',
    ],
    [
        'type_key' => 'IXC40', 'name' => 'Tipo IX C/40', 'soprannome' => null,
        'disp_surf_t' => 1144, 'disp_sub_t' => 1257,
        'speed_surf_kn' => 19.0, 'speed_sub_kn' => 7.3,
        'fuel_t' => 214.0,
        'range1_nm' => 13850, 'range1_kn' => 10.0, 'range2_nm' => null, 'range2_kn' => null,
        'sub_range_nm' => 63, 'sub_range_kn' => 4.0, 'sub_max_hours' => 1.4,
        'test_depth_m' => 100, 'crush_depth_min_m' => 200, 'crush_depth_max_m' => 230,
        'dive_time_s' => 37, 'crew_min' => 48, 'crew_max' => 56,
        'torpedoes' => 22, 'tubes_bow' => 4, 'tubes_stern' => 2,
        'deck_gun' => '10,5 cm SK C/32', 'provisions_days' => 60,
        'unlock_rank' => 6, 'playable' => 1,
        'fonte' => 'Specifiche Tipo IX C/40.',
        'confidence' => 'media',
        'note' => 'La versione con piu\' nafta del IX C: arriva ovunque, e ovunque e\' lento a sparire sott\'acqua.',
    ],
    [
        'type_key' => 'IXD2', 'name' => 'Tipo IX D2', 'soprannome' => null,
        'disp_surf_t' => 1616, 'disp_sub_t' => 1804,
        'speed_surf_kn' => 20.8, 'speed_sub_kn' => 6.9,
        'fuel_t' => 441.0,
        'range1_nm' => 23700, 'range1_kn' => 12.0, 'range2_nm' => null, 'range2_kn' => null,
        'sub_range_nm' => 57, 'sub_range_kn' => 4.0, 'sub_max_hours' => 1.3,
        'test_depth_m' => 100, 'crush_depth_min_m' => 200, 'crush_depth_max_m' => 230,
        'dive_time_s' => 45, 'crew_min' => 55, 'crew_max' => 63,
        'torpedoes' => 24, 'tubes_bow' => 4, 'tubes_stern' => 2,
        'deck_gun' => '10,5 cm SK C/32', 'provisions_days' => 90,
        'unlock_rank' => 8, 'playable' => 1,
        'fonte' => 'Specifiche Tipo IX D2, battello da crociera a lunghissimo raggio.',
        'confidence' => 'media',
        'note' => 'Il battello dell\'Oceano Indiano e del Sud Atlantico. Quarantacinque secondi per immergersi: in Biscaglia e\' una condanna.',
    ],
    [
        'type_key' => 'XXI', 'name' => 'Tipo XXI', 'soprannome' => 'Elektroboot',
        'disp_surf_t' => 1621, 'disp_sub_t' => 1819,
        'speed_surf_kn' => 15.6, 'speed_sub_kn' => 17.2,
        'fuel_t' => 250.0,
        'range1_nm' => 15500, 'range1_kn' => 10.0, 'range2_nm' => null, 'range2_kn' => null,
        'sub_range_nm' => 340, 'sub_range_kn' => 5.0, 'sub_max_hours' => 1.0,
        'test_depth_m' => 135, 'crush_depth_min_m' => 280, 'crush_depth_max_m' => 330,
        'dive_time_s' => 20, 'crew_min' => 55, 'crew_max' => 57,
        'torpedoes' => 23, 'tubes_bow' => 6, 'tubes_stern' => 0,
        'deck_gun' => null, 'provisions_days' => 90,
        'unlock_rank' => 12, 'playable' => 1,
        'fonte' => 'Specifiche Tipo XXI (1944-45): primo sommergibile progettato per navigare prevalentemente immerso.',
        'confidence' => 'media',
        'note' => 'Piu\' veloce sott\'acqua che in superficie, ricarica col respiratore, ricarica idraulica dei tubi. In servizio dal 1944: qui si ottiene a fine carriera, e la scheda lo dichiara.',
    ],
    [
        'type_key' => 'XIV', 'name' => 'Tipo XIV', 'soprannome' => 'Milchkuh (vacca da latte)',
        'disp_surf_t' => 1688, 'disp_sub_t' => 1932,
        'speed_surf_kn' => 14.4, 'speed_sub_kn' => 6.2,
        'fuel_t' => 986.0,
        'range1_nm' => 9300, 'range1_kn' => 12.0, 'range2_nm' => null, 'range2_kn' => null,
        'sub_range_nm' => 55, 'sub_range_kn' => 4.0, 'sub_max_hours' => 1.2,
        'test_depth_m' => 100, 'crush_depth_min_m' => 200, 'crush_depth_max_m' => 240,
        'dive_time_s' => 40, 'crew_min' => 53, 'crew_max' => 60,
        'torpedoes' => 4, 'tubes_bow' => 0, 'tubes_stern' => 0,
        'deck_gun' => null, 'provisions_days' => 120,
        'unlock_rank' => 0, 'playable' => 0,
        'fonte' => 'Specifiche Tipo XIV, battello cisterna di rifornimento d\'altura.',
        'confidence' => 'bassa',
        'note' => 'Non pilotabile: e\' l\'appuntamento in mezzo all\'oceano. Cede nafta, siluri, viveri e il medico di bordo — e per farlo restate fermi in superficie per ore.',
    ],
];
